[modules]
autoload=yes

; Specifically required for ARI to function
load => res_ari.so
load => res_ari_model.so
load => res_stasis.so
load => res_ari_asterisk.so
load => res_ari_channels.so
load => res_ari_events.so
load => res_http_websocket.so
